### PR TITLE
Provider detection checkbox

### LINKED ISSUE #191: Implement provider detection
Usage protocols change depending on the provider that is used. Currently, CogniCrypt_SAST only supports one CrySL rule set of usage protocols and is provider-agnostic. Extend it to detect the used provider and select the corresponding set of CrySL rules. If no rules are available for the detected provider, make it default to the set of rules for the providers that ship with the JCA.

Consult the [JCA](https://docs.oracle.com/javase/9/security/java-cryptography-architecture-jca-reference-guide.htm#JSSEC-GUID-2BCFDD85-D533-4E6C-8CE9-29990DEB0190) and [JCA provider](https://docs.oracle.com/javase/9/security/howtoimplaprovider.htm#JSSEC-GUID-C485394F-08C9-4D35-A245-1B82CDDBC031) documentations for ways to invoke (specific) providers.

### PR DESCRIPTION
**Pull request by enriozuni**
# Provider detection analysis checkbox

This PR implements the provider detection checkbox in the CogniCrypt's preference page of Eclipse. The provider detection analysis functionality is imported from the CryptoAnalysis repository. The latest changes in provider detection analysis, as well as many provider detection related headless tests, are found in this [PR](https://github.com/CROSSINGTUD/CryptoAnalysis/pull/185) which is waiting to be merged to _develop_ branch of CryptoAnalysis.

Fixes #191 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Firstly, many headless tests regarding provider detection analysis were done and the PR is located [here](https://github.com/CROSSINGTUD/CryptoAnalysis/pull/185). Furthermore, various JUnit tests are carried out [here](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/develop/CryptoAnalysis/src/test/java/tests/providerdetection). Lastly, numerous manual tests are made in inner Eclipse to prove the correctness of provider detection analysis. 

- [X] BragaCrypto headless tests on CryptoAnalyis repository
- [X] Provider detection JUnit tests on CryptoAnalysis repository
- [X] Various manual tests in inner Eclipse

**Test Configuration**:
* Eclipse Version: 2019-06
* Java Version: 1.8
* OS: Windows 10

# Checklist:

- [ ] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kruegers — APPROVED** [review]

**Comment by kruegers** [comment]
@krinara86 Can u please review the code and also test it on your machine? @enriozuni If Krishna needs some explanation of what the provider detection does, please give him a short introduction.
Thanks!

**Comment by krinara86** [comment]
I am in touch with @enriozuni I will review this.

**Comment by krinara86** [comment]
@kruegers Reviewed it and tested that it works on my machine as expected. Will wait for the build to be fixed and merge the pull request.

**Comment by kruegers** [comment]
Thanks @enriozuni and @krinara86 for preparing and reviewing the PR. The CI issue was thankfully unrelated to the PR.

**Pull request merged**
