### PR TITLE
Removing .project, .classpath and .prefs files and adding the extensi…

### PR DESCRIPTION
**Pull request by johspaeth**
…on to gitignore.

We are using maven, there is no need to keep these files in the repository.

### CODE REVIEW

**Comment by kruegers** [comment]
This appears impractical to me. The projects are still developed with Eclipse and without, say, a classpath file, Eclipse does not recognize which folders are which. Without the project files, one can also only import these projects as Maven projects, with them, they can be imported as regular Java projects or even through git import.

**Comment by johspaeth** [comment]
This is confusing. Do I need to import all projects as Java project? Or as maven? In any case, I get compile errors on importing! 

When I import the projects as maven - despite I cannot compile - there are automatic changes to the .classpath and .project files. One easily commit these changes and the project won't compile somewhere else.

**Comment by kruegers** [comment]
All ways should be fine although I usually import them through git import. Eclipse should recognize that they are a) Java projects, b) git projects, and c) Maven projects. In any case, what compiler errors are you getting?

**Comment by johspaeth** [comment]
The option "git import" detects the .project files and falls back to the normal Eclipse Java project import. Importing the project as maven however will change the .classfiles and .prefs files and I guess that is not the intended way? Have you tried it?

Anyhow, I am trying to update the [CryptoAnalysis.jar](https://github.com/eclipse-cognicrypt/CogniCrypt/tree/master/plugins/de.cognicrypt.core/lib) to a new version but don't really understand how to. Where do I need to change the file name? There are multiple location where CryptoAnalysis-1.0.0-jar-with-dependencies.jar is referenced.

**Comment by johspaeth** [comment]
I agree it does not make sense. Closing the pull request unmerged.

**Pull request closed without merging**
