### PR TITLE
Fix reading rulesets from eclipse installation directory

### PR DESCRIPTION
**Pull request by rakshitkr**
Signed-off-by: Rakshit Krishnappa Ravi <rakshitkrishnapparavi@gmail.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Eclipse Version:
* Java Version:
* OS:

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rakshitkr** [comment]
@kruegers Without this fix, the code generator reads all versions of jca rulesets from eclipse installation directory

**Comment by rakshitkr** [comment]
@kruegers The present code is reading ruleset from both eclipse installation directory as well as internal resources folder in core plugin. This would result in a list of duplicate rules. Since the code generation is based on latest jca ruleset, should we remove reading rules from internal resources folder completely?

**Comment by kruegers** [comment]
@rakshitkr AFAIK, the internal folder is for custom rules only. Is it used for anything else?

**Comment by rakshitkr** [comment]
> @rakshitkr AFAIK, the internal folder is for custom rules only. Is it used for anything else?
Oh okay... I still had the old JCA rules in the custom folder. Hence the generated list had many duplicates. I'll clear up my custom folder. Thanks for the clarification.

**Comment by rakshitkr** [comment]
@enriozuni Could you please test this fix on your machine? Thanks...

**Comment by enriozuni** [comment]
I tested the PR on my machine and is working as expected.

**Comment by rakshitkr** [comment]
@kruegers Please merge this PR. It has the below changes
-  the ruleset download directory changed to`$ECLIPSE_INSTALLATION_DIRECTORY/resources/CrySLRules/...`
- removed `LATEST_JCA_RULESET_PATH` from Constants because _getRuleVersions()_ fails during first instance when the rulesets aren't downloaded yet
- Added myself as co-author to f71e275 commit by @sritejakv since we both worked on it

**Review by kruegers — APPROVED** [review]

**Pull request merged**
